version: '3.8'

services:
  mailer-api:
    image: ghcr.io/tony-milukov/mailer_service/mailer-api:latest
    container_name: mailer-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    stdin_open: true
  mailer-worker:
    image: ghcr.io/tony-milukov/mailer_service/mailer-worker:latest
    container_name: mailer-worker
    restart: unless-stopped
    env_file:
      - .env
    stdin_open: true